version: '3'
services:
  blogtool:
    build: ./blogtool
    container_name: blogtool
    environment:
      - GIT_USER=$GIT_USER
      - GIT_EMAIL=$GIT_EMAIL
      
    # tty container -> host    output
    # stdin_opne host -> container    input
    tty: true
    stdin_open: true